import styled from 'styled-components';
import { HelloWorld, KIKI } from '@frontend-stack/shared/components';
import useTranslation from 'next-translate/useTranslation';
import setLanguage from 'next-translate/setLanguage';
import { Button } from 'react-native';

const StyledPage = styled.div`
  .page {
  }
`;

export function Index() {
  const { t, lang } = useTranslation('common');
  /*
   * Replace the elements below with your own.
   *
   * Note: The corresponding styles are in the ./index.styled-components file.
   */

  return (
    <StyledPage>
      <div className="wrapper">
        <h1 className="text-3xl font-bold underline p-10 bg-red-200">
          {t('common:hello')} from {t('common:brand')}
        </h1>

        <Button onPress={() => setLanguage('en')} title="ENGLISH" />
        <Button onPress={() => setLanguage('cn')} title="CHINESE" />
        <HelloWorld />
        <KIKI />
        <div className="flex min-h-screen justify-center items-center">
          <head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </head>

          <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
            <img
              className="w-full"
              src="https://tailwindcss.com/img/card-top.jpg"
              alt="Sunset in the mountains"
            />
            <div className="px-6 py-4">
              <div className="font-bold text-xl mb-2">Next + Tailwind ❤️</div>
              <p className="text-grey-darker text-base">
                Next and Tailwind CSS are a match made in heaven, check out this
                article on how you can combine these two for your next app.
              </p>
            </div>
          </div>
        </div>
      </div>
    </StyledPage>
  );
}

export default Index;
